# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Qase Framework CI & Allure Report

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Выберите тест-сьют для запуска:'
        required: true
        default: 'tests'
        type: choice
        options:
          - 'api-smoke'
          - 'ui-smoke'
          - 'api-regression'
          - 'ui-regression'
          - 'tests'

jobs:
  run-tests:
    name: Execute Tests & Publish Report
    runs-on: ubuntu-latest

    env:
      QASE_TOKEN: ${{ secrets.QASE_API_TOKEN }}
      USER_EMAIL: ${{ secrets.QASE_USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.QASE_USER_PASSWORD }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: |
          mvn clean test \
          -Dtoken=$QASE_TOKEN \
          -Duser=$USER_EMAIL \
          -Dpassword=$USER_PASSWORD \
          -Dmistral_api_key=$MISTRAL_API_KEY

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
